export const MSG_WINNER = 'Winner: $winner'
export const MSG_GOTO = 'Go to $place; $player{$row,$column}'
export const MSG_GAMESTART = 'Go to game start'
export const MSG_NEXT = 'Next player: $player'
export const MSG_DRAW = 'Draw: Play again!'